name: Template - Java on AWS EKS

on:
  push:
    branches: [development, staging, production]
    paths-ignore:
      - '.github/workflows/**'

  workflow_dispatch:

jobs:
  validate-oas:
    runs-on: ubuntu-latest
    container:
      image: shesse/redoc-cli:1.0.1
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Validate open api spec (redoc CLI)
        run: npx @redocly/cli lint oas/oas.yaml
        
  api-ui:
    uses: Blue-Express/bx_templates/.github/workflows/build-api-ui.yaml@blue
    needs: validate-oas
    with:
      environment: development #${{ github.ref_name }}
      namespace: dev-ns-{namespace}                   # Cambiar segun corresponda
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID  }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
      AWS_REGION: ${{ secrets.AWS_REGION  }}
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
      TOKEN_REPO_TEMPLATE: ${{ secrets.REPO_HELM_ACCESS }}
  
  sonar:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
         java-version: '17' # The JDK version to make available on the path.
         java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
         architecture: x64
         distribution: 'temurin'
     - name: Checkstyle
       run: mvn checkstyle:checkstyle -DskipTests
    # - name: Sonarqube
    #   run: mvn verify sonar:sonar -DskipTests -Dsonar.host.url=${{ secrets.SONARQUBE_DEV_URL }} -Dsonar.login=${{ secrets.SONARQUBE_DEV_TOKEN }}
     - name: SonarqubeV2
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
         SONAR_TOKEN: ${{ secrets.SONARQUBE_DEV_TOKEN_V2 }}
         SONAR_HOST_URL: ${{ secrets.SONARQUBE_DEV_URL_V2 }}
       run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ github.event.repository.name }}
     - name: Read value from Properties-file check Quality Gate
       id: read_property
       uses: christian-draeger/read-properties@1.0.1
       with:
         path: './target/sonar/report-task.txt'
         property: 'ceTaskId'
     - name: Show ceTaskId
       run: echo ${{ steps.read_property.outputs.value }}
     - name: Show Github ref
       run: echo ${{ github.ref }}
     - name: Break Build Quality Gate
       run: sh ./break_build.sh ${{ secrets.SONARQUBE_DEV_URL_V2 }} ${{ secrets.SONARQUBE_DEV_TOKEN_V2 }} ${{ steps.read_property.outputs.value }}

  build:
    uses: Blue-Express/bx_templates/.github/workflows/build-java17.yml@blue
    needs: [api-ui, sonar]
  push-img:
    uses: Blue-Express/bx_templates/.github/workflows/push-java.yml@blue
    needs: build
    with:
      environment: ${{ github.ref_name }}
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  deploy:
    uses: Blue-Express/bx_templates/.github/workflows/deploy-helm-java-api.yml@blue
    needs: push-img
    with:
      environment: ${{ github.ref_name }}
      namespace: ns-name                              # Reemplazar por el correspondiente
      path-values: helm/values-${{ github.ref_name }}.yml
      base-path: /api/domain/v1                       # Reemplazar
      liveness-path: /actuator/health
      liveness-initialDelay: '60'
      liveness-periodoSeconds: '10'
      liveness-timeoutSeconds: '20'
      ingress-enabled: true                           # true (expuesto) - false (interno)
      ingress-groupname: ingrz-namespace              # Reemplazar {namespace} por el {name} del NS
      # Recursos Default
      cpu-base: '10m'
      memory-base: '128Mi'
      cpu-limit: '500m'
      memory-limit: '512Mi'
      replicas: '1'
      # Límite Recursos Dev
      cpu-limit-dev: '500m'
      memory-limit-dev: '512Mi'
      replicas-dev: '1'
      # Límite Recursos Qa
      cpu-limit-qa: '200m'
      memory-limit-qa: '380Mi'
      replicas-qa: '1'
      # Límite Recursos Prod
      cpu-limit-prod: '200m'
      memory-limit-prod: '380Mi'
      replicas-prod: '1'
      
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_KUBECONFIG: ${{ secrets.AWS_KUBECONFIG }}
      TOKEN_REPO_TEMPLATE: ${{ secrets.REPO_HELM_ACCESS }}
      SECRETOS: ${{ toJSON(secrets) }}
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}

  api-mgnt:
    uses: Blue-Express/bx_templates/.github/workflows/kong.yml@blue
    needs: deploy
    with:
      environment: ${{ github.ref_name }}
      kong-srv-protocol: '"http"'
      kong-srv-host: ${{ needs.deploy.outputs.ingress }}
      kong-srv-port: '80'
      kong-cnsr: 'front-cnsr'
      kong-srv-path: '/api/domain/v1'               # Reemplazar con el mismo del {base-path}
      kong-rts-protocol: '"http","https"'
      kong-rts-path: '/api/domain/v1'               # Reemplazar con el mismo del {kong-srv-path} (expuesta a inet)
      kong-rts-methods: '"GET", "POST", "HEAD", "OPTIONS", "CONNECT"'
      kong-plugins: '"jwt-keycloak" "key-auth" "cors"'
      kong-cors-dev: '"http://localhost:3000","https://localhost:3000","https://dev.blue.cl"'
      kong-cors-qa: '"http://qa.blue.cl","https://qa.blue.cl"'
      kong-cors-prod: '"http://blue.cl","https://blue.cl"'
      kong-cors-methods: '"GET", "POST", "DELETE", "PATCH", "PUT", "HEAD", "OPTIONS", "TRACE", "CONNECT"'
      kong-jwt-allowed-iss: '/auth/realms/name'     # Si se encuentra habilitado {kong-plugins:  '"jwt-keycloak"}, se debe definir.
    secrets:
      TOKEN_REPO_TEMPLATE: ${{ secrets.REPO_HELM_ACCESS  }}
      KONG_HOST: ${{ secrets.KONG_HOST }}
      AWS_REGION: ${{ secrets.AWS_REGION  }}
      KEYCLOAK_HOST: ${{ secrets.KEYCLOAK_HOST  }}
