name: Template - Java Kafka Consumers on AWS EKS

on:
  push:
    branches: [development, staging, production]
    paths-ignore:
      - '.github/**'

  workflow_dispatch:

jobs:
  build:
    uses: Blue-Express/bx_templates/.github/workflows/build-java.yml@blue

  push-img:
    uses: Blue-Express/bx_templates/.github/workflows/push-java.yml@blue
    needs: build
    with:
      environment: ${{ github.ref_name }}
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  deploy:
    uses: Blue-Express/bx_templates/.github/workflows/deploy-helm-java-api.yml@blue
    needs: push-img
    with:
      environment: ${{ github.ref_name }}
      namespace: ns-name
      path-values: helm/values-${{ github.ref_name }}.yml
      base-path: /api/domain/v1
      liveness-path: /actuator/health
      liveness-initialDelay: '60'
      liveness-periodoSeconds: '10'
      liveness-timeoutSeconds: '20'
      cpu-base: '100m'
      memory-base: '128Mi'
      cpu-limit: '200m'
      memory-limit: '380Mi'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_KUBECONFIG: ${{ secrets.AWS_KUBECONFIG }}
      TOKEN_REPO_TEMPLATE: ${{ secrets.REPO_HELM_ACCESS }}
      SECRETOS: ${{ toJSON(secrets) }}
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
