name: Template - Node.js on AWS EKS

on:
  push:
    branches: [development, staging, production]
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  sonar:
    uses: Blue-Express/bx_templates/.github/workflows/pr-sonar-node.yml@blue
    secrets:
      SONARQUBE_DEV_URL: ${{ secrets.SONARQUBE_DEV_URL }}
      SONARQUBE_DEV_TOKEN: ${{ secrets.SONARQUBE_DEV_TOKEN }}
      TOKEN_REPO_TEMPLATE: ${{ secrets.TOKEN_REPO_TEMPLATE }}
  
  build:
    uses: Example-Express/bx_templates/.github/workflows/build-and-push-nodejs.yml@blue
    needs: sonar
    with:
      environment: ${{ github.ref_name }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID  }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
      AWS_REGION: ${{ secrets.AWS_REGION  }}
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
      
  deploy:
    uses: Example-Express/bx_templates/.github/workflows/deploy-helm-node-api.yml@blue
    needs: build
    with:
      environment: ${{ github.ref_name }}
      namespace: ns-development                              # Reemplazar al Correspondiente
      path-values: helm/values-${{ github.ref_name }}.yml
      base-path: /api/development/v1                         # Definir de acuerdo al live path de la aplicación   
      
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_KUBECONFIG: ${{ secrets.AWS_KUBECONFIG }}
      TOKEN_REPO_TEMPLATE: ${{ secrets.REPO_HELM_ACCESS }}
      SECRETOS: ${{ toJSON(secrets) }}
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
