name: you-name-here

on:
  push:
    branches: [development, staging, production]
    paths-ignore:
      - '.github/workflows/**'

  workflow_dispatch:

jobs:
  sonar:
    runs-on: ubuntu-latest
    environment:
      name: "development"
      url: https://sonarqube.infra.blue.cl/dashboard?id=${{ github.event.repository.name }}
    steps:      
      - uses: actions/checkout@v3
      - name: SonarQube Scan
        uses: Blue-Express/sonar-scan-action@master
        
        id: check
        with:
          sonarqube_url: ${{ secrets.SONARQUBE_DEV_URL_V2 }}
          sonarqube_token: ${{ secrets.SONARQUBE_DEV_TOKEN_V2 }}
          projectKey: ${{ github.event.repository.name }}

  build:
    uses: Blue-Express/bx_templates/.github/workflows/build-and-push-nodejs.yml@blue
    needs: sonar
    with:
      install-pkg: "npm"
      environment: ${{ github.ref_name }}
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

### deploy cronjob
  deploy:
    uses: Blue-Express/bx_templates/.github/workflows/deploy-helm-node-cronjob.yml@blue
    needs: build
    with:
      schedule: '0 * * * *'
      environment: ${{ github.ref_name }}
      namespace: ns-namespace                               # Reemplazar {namespace} por el {name} del NS
      path-values: helm/values-${{ github.ref_name }}.yml
      success-history: '3'
      failed-history: '3'
      seconds-finished: '100'
      backoff-limit: '3'
      concurrencyPolicy: Forbid
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_KUBECONFIG: ${{ secrets.AWS_KUBECONFIG }}
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
      TOKEN_REPO_TEMPLATE: ${{ secrets.REPO_HELM_ACCESS }}
      SECRETOS: ${{ toJSON(secrets) }}
