name: Template - Java Kafka Consumers on AWS EKS

on:
  push:
    branches: [development, staging, production]
    paths-ignore:
      - '.github/workflows/**'

  workflow_dispatch:

jobs:
  sonar:
    uses: Blue-Express/bx_templates/.github/workflows/pr-sonar-java.yml@blue
    secrets:
      SONARQUBE_DEV_URL: ${{ secrets.SONARQUBE_DEV_URL }}
      SONARQUBE_DEV_TOKEN: ${{ secrets.SONARQUBE_DEV_TOKEN }}
      TOKEN_REPO_TEMPLATE: ${{ secrets.TOKEN_REPO_TEMPLATE }}

  build:
    uses: Blue-Express/bx_templates/.github/workflows/build-java.yml@blue
    needs: sonar

  push-img:
    uses: Blue-Express/bx_templates/.github/workflows/push-java.yml@blue
    needs: build
    with:
      environment: ${{ github.ref_name }}
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

### deploy consumer
  deploy-csmr00:
    uses: Blue-Express/bx_templates/.github/workflows/deploy-helm-java-api.yml@blue
    needs: push-img
    with:
      suffix: -csmr00
      cert-path: true
      replicas: '1'
      environment: ${{ github.ref_name }}
      namespace: ns-name
      path-values: helm/values-${{ github.ref_name }}-csmr00.yml
      base-path: /api/domain/v1/csmr00
      liveness-path: /actuator/health
      liveness-initialDelay: '90'
      liveness-periodoSeconds: '60'
      liveness-timeoutSeconds: '20'
      cpu-base: '100m'
      memory-base: '128Mi'
      cpu-limit: '200m'
      memory-limit: '380Mi'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_KUBECONFIG: ${{ secrets.AWS_KUBECONFIG }}
      TOKEN_REPO_TEMPLATE: ${{ secrets.REPO_HELM_ACCESS }}
      SECRETOS: ${{ toJSON(secrets) }}
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}

### deploy consumer retry 01
  deploy-csmr01:
    uses: Blue-Express/bx_templates/.github/workflows/deploy-helm-java-api.yml@blue
    needs: push-img
    with:
      suffix: -csmr01
      cert-path: true
      replicas: '1'
      environment: ${{ github.ref_name }}
      namespace: ns-name
      path-values: helm/values-${{ github.ref_name }}-csmr01.yml
      base-path: /api/domain/v1/csmr01
      liveness-path: /actuator/health
      liveness-initialDelay: '90'
      liveness-periodoSeconds: '60'
      liveness-timeoutSeconds: '20'
      cpu-base: '100m'
      memory-base: '128Mi'
      cpu-limit: '200m'
      memory-limit: '380Mi'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_KUBECONFIG: ${{ secrets.AWS_KUBECONFIG }}
      TOKEN_REPO_TEMPLATE: ${{ secrets.REPO_HELM_ACCESS }}
      SECRETOS: ${{ toJSON(secrets) }}
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}

### deploy consumer retry 02
  deploy-csmr02:
    uses: Blue-Express/bx_templates/.github/workflows/deploy-helm-java-api.yml@blue
    needs: push-img
    with:
      suffix: -csmr02
      cert-path: true
      replicas: '1'
      environment: ${{ github.ref_name }}
      namespace: ns-name
      path-values: helm/values-${{ github.ref_name }}-csmr02.yml
      base-path: /api/domain/v1/csmr02
      liveness-path: /actuator/health
      liveness-initialDelay: '90'
      liveness-periodoSeconds: '60'
      liveness-timeoutSeconds: '20'
      cpu-base: '100m'
      memory-base: '128Mi'
      cpu-limit: '200m'
      memory-limit: '380Mi'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_KUBECONFIG: ${{ secrets.AWS_KUBECONFIG }}
      TOKEN_REPO_TEMPLATE: ${{ secrets.REPO_HELM_ACCESS }}
      SECRETOS: ${{ toJSON(secrets) }}
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
