name: Template - Node.js Consumer on AWS EKS

on:
  push:
    branches: [development, staging, production]
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  sonar:
    runs-on: ubuntu-latest
    environment:
      name: 'development'
      url: https://desa-sonar.bluex.cl/dashboard?id=${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v3
      - name: SonarQube Scan
        uses: Blue-Express/sonar-scan-action@master

        id: check
        with:
          sonarqube_url: ${{ secrets.SONARQUBE_DEV_URL }}
          sonarqube_token: ${{ secrets.SONARQUBE_DEV_TOKEN }}
          projectKey: ${{ github.event.repository.name }}
  
  build:
    uses: Blue-Express/bx_templates/.github/workflows/build-and-push-nodejs.yml@blue
    needs: sonar
    with:
      environment: ${{ github.ref_name }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID  }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
      AWS_REGION: ${{ secrets.AWS_REGION  }}
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
      
  deploy:
    uses: Blue-Express/bx_templates/.github/workflows/deploy-helm-node-api.yml@blue
    needs: build
    with:
      # iamServiceAccount:            # Habilitar y agregar de ser necesario
      environment: ${{ github.ref_name }}
      namespace: ns-{namespace}       # Agregar namespace
      path-values: helm/values-${{ github.ref_name }}.yml
      base-path: /api/path/v1    # Modificar según corresponda
      liveness-path: /health/liveness
      liveness-initialDelay: '180'
      liveness-periodoSeconds: '45'
      liveness-timeoutSeconds: '20'
      # ingress-enabled: true                           # true (expuesto) - false (interno)
      # ingress-groupname: ingrz-{namespace}            # Habilitar si corresponde
      # iamServiceAccount: default
      # Recursos Default
      cpu-base: '10m'
      memory-base: '64Mi'
      cpu-limit: '400m'
      memory-limit: '500Mi'
      replicas: '1'
      # Límite Recursos Dev
      cpu-limit-dev: '200m'
      memory-limit-dev: '380Mi'
      replicas-dev: '1'
      # Límite Recursos Qa
      cpu-limit-qa: '400m'
      memory-limit-qa: '380Mi'
      replicas-qa: '1'
      # Límite Recursos Prod
      cpu-limit-prod: '400m'
      memory-limit-prod: '380Mi'
      replicas-prod: '3' 
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_KUBECONFIG: ${{ secrets.AWS_KUBECONFIG }}
      TOKEN_REPO_TEMPLATE: ${{ secrets.REPO_HELM_ACCESS }}
      SECRETOS: ${{ toJSON(secrets) }}
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
