name: 00 Template - AWS Cloudfront

on:
  push:
    branches: [development, staging, production]
    paths-ignore:
      - '.github/**'

  workflow_dispatch:

jobs:
  build:
    uses: Blue-Express/bx_templates/.github/workflows/build-react.yml@blue
    with:
      path-values: values/.env.${{ github.ref_name }}
      install-pkg: none #npm/yarn
      build-path: html
    secrets:
      SECRETOS: ${{ toJSON(secrets) }}

  deploy:
    uses: Blue-Express/bx_templates/.github/workflows/deploy-cloudfront.yml@blue
    needs: build
    with:
      environment: ${{ github.ref_name }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID  }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
      AWS_REGION: ${{ secrets.AWS_REGION  }}
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
      TOKEN_REPO_TEMPLATE: ${{ secrets.REPO_HELM_ACCESS  }}

  setting:
    uses: Blue-Express/bx_templates/.github/workflows/route53-cert-mngr.yml@blue
    needs: deploy
    with:
      domain: blue.cl
      subdomain: subdomain
      environment: ${{ github.ref_name }}
      cname: ${{ needs.deploy.outputs.domain }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID  }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
      AWS_REGION: ${{ secrets.AWS_REGION  }}
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}

  conf:
    uses: Blue-Express/bx_templates/.github/workflows/conf-cloudfront.yml@blue
    needs: setting
    with:
      environment: ${{ github.ref_name }}
      distribution-id: ${{ needs.deploy.outputs.distribution }}
      alt-domain: ${{ needs.setting.outputs.domain }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID  }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
      AWS_REGION: ${{ secrets.AWS_REGION  }}
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}
      TOKEN_REPO_TEMPLATE: ${{ secrets.REPO_HELM_ACCESS  }}
