name: Datadog Dashboard
on:
  #push:
  #  branches: [development, staging, production]
  #  paths-ignore:
  #    - '.github/**'

  workflow_run:
    workflows: [Template - JAVA/NodeJS on AWS EKS]
    types: [completed]

  workflow_dispatch:

jobs:
  datadog:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: Blue-Express/bx_templates/.github/workflows/dd-dashboard-srv.yml@blue
    with:
      environment: ${{ github.ref_name }}
    secrets:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      DD_APPLICATION_KEY: ${{ secrets.DD_APPLICATION_KEY }}
      TOKEN_REPO_TEMPLATE: ${{ secrets.REPO_HELM_ACCESS }}
      AWS_KUBECONFIG: ${{ secrets.AWS_KUBECONFIG }}