# This is a initial setup enmviroment.
# You can delete this file once executed in your repository
name: create-env-repo

on:
  push:
    branches: ['*']
  workflow_dispatch:
    secrets:
      TOKEN_REPO_TEMPLATE:

jobs:
  sync-env:
    uses: Blue-Express/bx_templates/.github/workflows/tmpl-repo-sync-env.yml@blue
